# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Run and Test

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and Test
      run: mvn -f pom.xml test
    - name: Build Test and Generate Coverage
      run: mvn -f pom.xml test jacoco:report
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./target/site/jacoco
        retention-days: 1
    - name: Build Sender and Receiver Packages
      run:  mvn -B package --file pom.xml -Dmaven.test.skip=true
    - name: Pipe sender and receiver jars
      run: java -jar target/BMSSender.jar | java -jar target/BMSReceiver.jar
